/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicVolunteerRouteImport } from './routes/_public.volunteer'
import { Route as PublicTermsRouteImport } from './routes/_public.terms'
import { Route as PublicRegisterRouteImport } from './routes/_public.register'
import { Route as PublicPublicationsRouteImport } from './routes/_public.publications'
import { Route as PublicPrivacyRouteImport } from './routes/_public.privacy'
import { Route as PublicPoliticalPositionRouteImport } from './routes/_public.political-position'
import { Route as PublicPartyPositionRouteImport } from './routes/_public.party-position'
import { Route as PublicLocalGroupRouteImport } from './routes/_public.local-group'
import { Route as PublicListingsRouteImport } from './routes/_public.listings'
import { Route as PublicFaqRouteImport } from './routes/_public.faq'
import { Route as PublicEventsRouteImport } from './routes/_public.events'
import { Route as PublicDonateRouteImport } from './routes/_public.donate'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicCareersRouteImport } from './routes/_public.careers'
import { Route as PublicBlogRouteImport } from './routes/_public.blog'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated.portal'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as PublicSharedUiVolunteerRouteImport } from './routes/_public.shared-ui.volunteer'
import { Route as PublicSharedUiTermsRouteImport } from './routes/_public.shared-ui.terms'
import { Route as PublicSharedUiRegisterRouteImport } from './routes/_public.shared-ui.register'
import { Route as PublicSharedUiPublicationsRouteImport } from './routes/_public.shared-ui.publications'
import { Route as PublicSharedUiPrivacyRouteImport } from './routes/_public.shared-ui.privacy'
import { Route as PublicSharedUiPoliticalPositionRouteImport } from './routes/_public.shared-ui.political-position'
import { Route as PublicSharedUiPartyPositionRouteImport } from './routes/_public.shared-ui.party-position'
import { Route as PublicSharedUiLocalGroupRouteImport } from './routes/_public.shared-ui.local-group'
import { Route as PublicSharedUiListingsRouteImport } from './routes/_public.shared-ui.listings'
import { Route as PublicSharedUiFaqRouteImport } from './routes/_public.shared-ui.faq'
import { Route as PublicSharedUiEventsRouteImport } from './routes/_public.shared-ui.events'
import { Route as PublicSharedUiDonateRouteImport } from './routes/_public.shared-ui.donate'
import { Route as PublicSharedUiContactRouteImport } from './routes/_public.shared-ui.contact'
import { Route as PublicSharedUiCareersRouteImport } from './routes/_public.shared-ui.careers'
import { Route as PublicSharedUiBlogRouteImport } from './routes/_public.shared-ui.blog'
import { Route as PublicSharedUiAboutRouteImport } from './routes/_public.shared-ui.about'
import { Route as PublicEventsIdRouteImport } from './routes/_public.events.$id'
import { Route as PublicBlogIdRouteImport } from './routes/_public.blog.$id'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated.admin.dashboard'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as PublicSharedUiEventsIdRouteImport } from './routes/_public.shared-ui.events.$id'
import { Route as PublicSharedUiBlogIdRouteImport } from './routes/_public.shared-ui.blog.$id'
import { Route as PublicEventsIdRegisterRouteImport } from './routes/_public.events.$id.register'
import { Route as AuthenticatedAdminUiVolunteerRouteImport } from './routes/_authenticated.admin.ui.volunteer'
import { Route as AuthenticatedAdminUiUsersRouteImport } from './routes/_authenticated.admin.ui.users'
import { Route as AuthenticatedAdminUiSettingsRouteImport } from './routes/_authenticated.admin.ui.settings'
import { Route as AuthenticatedAdminUiRolesRouteImport } from './routes/_authenticated.admin.ui.roles'
import { Route as AuthenticatedAdminUiReportsRouteImport } from './routes/_authenticated.admin.ui.reports'
import { Route as AuthenticatedAdminUiMerchandiseRouteImport } from './routes/_authenticated.admin.ui.merchandise'
import { Route as AuthenticatedAdminUiMembersRouteImport } from './routes/_authenticated.admin.ui.members'
import { Route as AuthenticatedAdminUiLocalGroupsRouteImport } from './routes/_authenticated.admin.ui.local-groups'
import { Route as AuthenticatedAdminUiJobsRouteImport } from './routes/_authenticated.admin.ui.jobs'
import { Route as AuthenticatedAdminUiEventsRouteImport } from './routes/_authenticated.admin.ui.events'
import { Route as AuthenticatedAdminUiDonationsRouteImport } from './routes/_authenticated.admin.ui.donations'
import { Route as AuthenticatedAdminUiCmsRouteImport } from './routes/_authenticated.admin.ui.cms'
import { Route as AuthenticatedAdminUiBlogsRouteImport } from './routes/_authenticated.admin.ui.blogs'
import { Route as AuthenticatedAdminUiAuditTrailsRouteImport } from './routes/_authenticated.admin.ui.audit-trails'
import { Route as AuthenticatedAdminUiAspirantsRouteImport } from './routes/_authenticated.admin.ui.aspirants'
import { Route as AuthenticatedAdminUiApplicationsRouteImport } from './routes/_authenticated.admin.ui.applications'
import { Route as AuthenticatedAdminUiAdminUsersRouteImport } from './routes/_authenticated.admin.ui.admin-users'
import { Route as PublicSharedUiEventsIdRegisterRouteImport } from './routes/_public.shared-ui.events.$id.register'
import { Route as AuthenticatedAdminUiJobsJobIdApplicationsRouteImport } from './routes/_authenticated.admin.ui.jobs.$jobId.applications'

const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicVolunteerRoute = PublicVolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPublicationsRoute = PublicPublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPoliticalPositionRoute = PublicPoliticalPositionRouteImport.update({
  id: '/political-position',
  path: '/political-position',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPartyPositionRoute = PublicPartyPositionRouteImport.update({
  id: '/party-position',
  path: '/party-position',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLocalGroupRoute = PublicLocalGroupRouteImport.update({
  id: '/local-group',
  path: '/local-group',
  getParentRoute: () => PublicRoute,
} as any)
const PublicListingsRoute = PublicListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEventsRoute = PublicEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDonateRoute = PublicDonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCareersRoute = PublicCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogRoute = PublicBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicSharedUiVolunteerRoute = PublicSharedUiVolunteerRouteImport.update({
  id: '/shared-ui/volunteer',
  path: '/shared-ui/volunteer',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSharedUiTermsRoute = PublicSharedUiTermsRouteImport.update({
  id: '/shared-ui/terms',
  path: '/shared-ui/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSharedUiRegisterRoute = PublicSharedUiRegisterRouteImport.update({
  id: '/shared-ui/register',
  path: '/shared-ui/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSharedUiPublicationsRoute =
  PublicSharedUiPublicationsRouteImport.update({
    id: '/shared-ui/publications',
    path: '/shared-ui/publications',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicSharedUiPrivacyRoute = PublicSharedUiPrivacyRouteImport.update({
  id: '/shared-ui/privacy',
  path: '/shared-ui/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSharedUiPoliticalPositionRoute =
  PublicSharedUiPoliticalPositionRouteImport.update({
    id: '/shared-ui/political-position',
    path: '/shared-ui/political-position',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicSharedUiPartyPositionRoute =
  PublicSharedUiPartyPositionRouteImport.update({
    id: '/shared-ui/party-position',
    path: '/shared-ui/party-position',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicSharedUiLocalGroupRoute =
  PublicSharedUiLocalGroupRouteImport.update({
    id: '/shared-ui/local-group',
    path: '/shared-ui/local-group',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicSharedUiListingsRoute = PublicSharedUiListingsRouteImport.update({
  id: '/shared-ui/listings',
  path: '/shared-ui/listings',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSharedUiFaqRoute = PublicSharedUiFaqRouteImport.update({
  id: '/shared-ui/faq',
  path: '/shared-ui/faq',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSharedUiEventsRoute = PublicSharedUiEventsRouteImport.update({
  id: '/shared-ui/events',
  path: '/shared-ui/events',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSharedUiDonateRoute = PublicSharedUiDonateRouteImport.update({
  id: '/shared-ui/donate',
  path: '/shared-ui/donate',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSharedUiContactRoute = PublicSharedUiContactRouteImport.update({
  id: '/shared-ui/contact',
  path: '/shared-ui/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSharedUiCareersRoute = PublicSharedUiCareersRouteImport.update({
  id: '/shared-ui/careers',
  path: '/shared-ui/careers',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSharedUiBlogRoute = PublicSharedUiBlogRouteImport.update({
  id: '/shared-ui/blog',
  path: '/shared-ui/blog',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSharedUiAboutRoute = PublicSharedUiAboutRouteImport.update({
  id: '/shared-ui/about',
  path: '/shared-ui/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEventsIdRoute = PublicEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicEventsRoute,
} as any)
const PublicBlogIdRoute = PublicBlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicBlogRoute,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicSharedUiEventsIdRoute = PublicSharedUiEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicSharedUiEventsRoute,
} as any)
const PublicSharedUiBlogIdRoute = PublicSharedUiBlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicSharedUiBlogRoute,
} as any)
const PublicEventsIdRegisterRoute = PublicEventsIdRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicEventsIdRoute,
} as any)
const AuthenticatedAdminUiVolunteerRoute =
  AuthenticatedAdminUiVolunteerRouteImport.update({
    id: '/ui/volunteer',
    path: '/ui/volunteer',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUiUsersRoute =
  AuthenticatedAdminUiUsersRouteImport.update({
    id: '/ui/users',
    path: '/ui/users',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUiSettingsRoute =
  AuthenticatedAdminUiSettingsRouteImport.update({
    id: '/ui/settings',
    path: '/ui/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUiRolesRoute =
  AuthenticatedAdminUiRolesRouteImport.update({
    id: '/ui/roles',
    path: '/ui/roles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUiReportsRoute =
  AuthenticatedAdminUiReportsRouteImport.update({
    id: '/ui/reports',
    path: '/ui/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUiMerchandiseRoute =
  AuthenticatedAdminUiMerchandiseRouteImport.update({
    id: '/ui/merchandise',
    path: '/ui/merchandise',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUiMembersRoute =
  AuthenticatedAdminUiMembersRouteImport.update({
    id: '/ui/members',
    path: '/ui/members',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUiLocalGroupsRoute =
  AuthenticatedAdminUiLocalGroupsRouteImport.update({
    id: '/ui/local-groups',
    path: '/ui/local-groups',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUiJobsRoute =
  AuthenticatedAdminUiJobsRouteImport.update({
    id: '/ui/jobs',
    path: '/ui/jobs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUiEventsRoute =
  AuthenticatedAdminUiEventsRouteImport.update({
    id: '/ui/events',
    path: '/ui/events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUiDonationsRoute =
  AuthenticatedAdminUiDonationsRouteImport.update({
    id: '/ui/donations',
    path: '/ui/donations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUiCmsRoute = AuthenticatedAdminUiCmsRouteImport.update({
  id: '/ui/cms',
  path: '/ui/cms',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUiBlogsRoute =
  AuthenticatedAdminUiBlogsRouteImport.update({
    id: '/ui/blogs',
    path: '/ui/blogs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUiAuditTrailsRoute =
  AuthenticatedAdminUiAuditTrailsRouteImport.update({
    id: '/ui/audit-trails',
    path: '/ui/audit-trails',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUiAspirantsRoute =
  AuthenticatedAdminUiAspirantsRouteImport.update({
    id: '/ui/aspirants',
    path: '/ui/aspirants',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUiApplicationsRoute =
  AuthenticatedAdminUiApplicationsRouteImport.update({
    id: '/ui/applications',
    path: '/ui/applications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUiAdminUsersRoute =
  AuthenticatedAdminUiAdminUsersRouteImport.update({
    id: '/ui/admin-users',
    path: '/ui/admin-users',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const PublicSharedUiEventsIdRegisterRoute =
  PublicSharedUiEventsIdRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => PublicSharedUiEventsIdRoute,
  } as any)
const AuthenticatedAdminUiJobsJobIdApplicationsRoute =
  AuthenticatedAdminUiJobsJobIdApplicationsRouteImport.update({
    id: '/$jobId/applications',
    path: '/$jobId/applications',
    getParentRoute: () => AuthenticatedAdminUiJobsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/portal': typeof AuthenticatedPortalRoute
  '/about': typeof PublicAboutRoute
  '/blog': typeof PublicBlogRouteWithChildren
  '/careers': typeof PublicCareersRoute
  '/contact': typeof PublicContactRoute
  '/donate': typeof PublicDonateRoute
  '/events': typeof PublicEventsRouteWithChildren
  '/faq': typeof PublicFaqRoute
  '/listings': typeof PublicListingsRoute
  '/local-group': typeof PublicLocalGroupRoute
  '/party-position': typeof PublicPartyPositionRoute
  '/political-position': typeof PublicPoliticalPositionRoute
  '/privacy': typeof PublicPrivacyRoute
  '/publications': typeof PublicPublicationsRoute
  '/register': typeof PublicRegisterRoute
  '/terms': typeof PublicTermsRoute
  '/volunteer': typeof PublicVolunteerRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/blog/$id': typeof PublicBlogIdRoute
  '/events/$id': typeof PublicEventsIdRouteWithChildren
  '/shared-ui/about': typeof PublicSharedUiAboutRoute
  '/shared-ui/blog': typeof PublicSharedUiBlogRouteWithChildren
  '/shared-ui/careers': typeof PublicSharedUiCareersRoute
  '/shared-ui/contact': typeof PublicSharedUiContactRoute
  '/shared-ui/donate': typeof PublicSharedUiDonateRoute
  '/shared-ui/events': typeof PublicSharedUiEventsRouteWithChildren
  '/shared-ui/faq': typeof PublicSharedUiFaqRoute
  '/shared-ui/listings': typeof PublicSharedUiListingsRoute
  '/shared-ui/local-group': typeof PublicSharedUiLocalGroupRoute
  '/shared-ui/party-position': typeof PublicSharedUiPartyPositionRoute
  '/shared-ui/political-position': typeof PublicSharedUiPoliticalPositionRoute
  '/shared-ui/privacy': typeof PublicSharedUiPrivacyRoute
  '/shared-ui/publications': typeof PublicSharedUiPublicationsRoute
  '/shared-ui/register': typeof PublicSharedUiRegisterRoute
  '/shared-ui/terms': typeof PublicSharedUiTermsRoute
  '/shared-ui/volunteer': typeof PublicSharedUiVolunteerRoute
  '/admin/ui/admin-users': typeof AuthenticatedAdminUiAdminUsersRoute
  '/admin/ui/applications': typeof AuthenticatedAdminUiApplicationsRoute
  '/admin/ui/aspirants': typeof AuthenticatedAdminUiAspirantsRoute
  '/admin/ui/audit-trails': typeof AuthenticatedAdminUiAuditTrailsRoute
  '/admin/ui/blogs': typeof AuthenticatedAdminUiBlogsRoute
  '/admin/ui/cms': typeof AuthenticatedAdminUiCmsRoute
  '/admin/ui/donations': typeof AuthenticatedAdminUiDonationsRoute
  '/admin/ui/events': typeof AuthenticatedAdminUiEventsRoute
  '/admin/ui/jobs': typeof AuthenticatedAdminUiJobsRouteWithChildren
  '/admin/ui/local-groups': typeof AuthenticatedAdminUiLocalGroupsRoute
  '/admin/ui/members': typeof AuthenticatedAdminUiMembersRoute
  '/admin/ui/merchandise': typeof AuthenticatedAdminUiMerchandiseRoute
  '/admin/ui/reports': typeof AuthenticatedAdminUiReportsRoute
  '/admin/ui/roles': typeof AuthenticatedAdminUiRolesRoute
  '/admin/ui/settings': typeof AuthenticatedAdminUiSettingsRoute
  '/admin/ui/users': typeof AuthenticatedAdminUiUsersRoute
  '/admin/ui/volunteer': typeof AuthenticatedAdminUiVolunteerRoute
  '/events/$id/register': typeof PublicEventsIdRegisterRoute
  '/shared-ui/blog/$id': typeof PublicSharedUiBlogIdRoute
  '/shared-ui/events/$id': typeof PublicSharedUiEventsIdRouteWithChildren
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/shared-ui/events/$id/register': typeof PublicSharedUiEventsIdRegisterRoute
  '/admin/ui/jobs/$jobId/applications': typeof AuthenticatedAdminUiJobsJobIdApplicationsRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/portal': typeof AuthenticatedPortalRoute
  '/about': typeof PublicAboutRoute
  '/blog': typeof PublicBlogRouteWithChildren
  '/careers': typeof PublicCareersRoute
  '/contact': typeof PublicContactRoute
  '/donate': typeof PublicDonateRoute
  '/events': typeof PublicEventsRouteWithChildren
  '/faq': typeof PublicFaqRoute
  '/listings': typeof PublicListingsRoute
  '/local-group': typeof PublicLocalGroupRoute
  '/party-position': typeof PublicPartyPositionRoute
  '/political-position': typeof PublicPoliticalPositionRoute
  '/privacy': typeof PublicPrivacyRoute
  '/publications': typeof PublicPublicationsRoute
  '/register': typeof PublicRegisterRoute
  '/terms': typeof PublicTermsRoute
  '/volunteer': typeof PublicVolunteerRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/blog/$id': typeof PublicBlogIdRoute
  '/events/$id': typeof PublicEventsIdRouteWithChildren
  '/shared-ui/about': typeof PublicSharedUiAboutRoute
  '/shared-ui/blog': typeof PublicSharedUiBlogRouteWithChildren
  '/shared-ui/careers': typeof PublicSharedUiCareersRoute
  '/shared-ui/contact': typeof PublicSharedUiContactRoute
  '/shared-ui/donate': typeof PublicSharedUiDonateRoute
  '/shared-ui/events': typeof PublicSharedUiEventsRouteWithChildren
  '/shared-ui/faq': typeof PublicSharedUiFaqRoute
  '/shared-ui/listings': typeof PublicSharedUiListingsRoute
  '/shared-ui/local-group': typeof PublicSharedUiLocalGroupRoute
  '/shared-ui/party-position': typeof PublicSharedUiPartyPositionRoute
  '/shared-ui/political-position': typeof PublicSharedUiPoliticalPositionRoute
  '/shared-ui/privacy': typeof PublicSharedUiPrivacyRoute
  '/shared-ui/publications': typeof PublicSharedUiPublicationsRoute
  '/shared-ui/register': typeof PublicSharedUiRegisterRoute
  '/shared-ui/terms': typeof PublicSharedUiTermsRoute
  '/shared-ui/volunteer': typeof PublicSharedUiVolunteerRoute
  '/admin/ui/admin-users': typeof AuthenticatedAdminUiAdminUsersRoute
  '/admin/ui/applications': typeof AuthenticatedAdminUiApplicationsRoute
  '/admin/ui/aspirants': typeof AuthenticatedAdminUiAspirantsRoute
  '/admin/ui/audit-trails': typeof AuthenticatedAdminUiAuditTrailsRoute
  '/admin/ui/blogs': typeof AuthenticatedAdminUiBlogsRoute
  '/admin/ui/cms': typeof AuthenticatedAdminUiCmsRoute
  '/admin/ui/donations': typeof AuthenticatedAdminUiDonationsRoute
  '/admin/ui/events': typeof AuthenticatedAdminUiEventsRoute
  '/admin/ui/jobs': typeof AuthenticatedAdminUiJobsRouteWithChildren
  '/admin/ui/local-groups': typeof AuthenticatedAdminUiLocalGroupsRoute
  '/admin/ui/members': typeof AuthenticatedAdminUiMembersRoute
  '/admin/ui/merchandise': typeof AuthenticatedAdminUiMerchandiseRoute
  '/admin/ui/reports': typeof AuthenticatedAdminUiReportsRoute
  '/admin/ui/roles': typeof AuthenticatedAdminUiRolesRoute
  '/admin/ui/settings': typeof AuthenticatedAdminUiSettingsRoute
  '/admin/ui/users': typeof AuthenticatedAdminUiUsersRoute
  '/admin/ui/volunteer': typeof AuthenticatedAdminUiVolunteerRoute
  '/events/$id/register': typeof PublicEventsIdRegisterRoute
  '/shared-ui/blog/$id': typeof PublicSharedUiBlogIdRoute
  '/shared-ui/events/$id': typeof PublicSharedUiEventsIdRouteWithChildren
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/shared-ui/events/$id/register': typeof PublicSharedUiEventsIdRegisterRoute
  '/admin/ui/jobs/$jobId/applications': typeof AuthenticatedAdminUiJobsJobIdApplicationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/blog': typeof PublicBlogRouteWithChildren
  '/_public/careers': typeof PublicCareersRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/donate': typeof PublicDonateRoute
  '/_public/events': typeof PublicEventsRouteWithChildren
  '/_public/faq': typeof PublicFaqRoute
  '/_public/listings': typeof PublicListingsRoute
  '/_public/local-group': typeof PublicLocalGroupRoute
  '/_public/party-position': typeof PublicPartyPositionRoute
  '/_public/political-position': typeof PublicPoliticalPositionRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/publications': typeof PublicPublicationsRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_public/volunteer': typeof PublicVolunteerRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_public/blog/$id': typeof PublicBlogIdRoute
  '/_public/events/$id': typeof PublicEventsIdRouteWithChildren
  '/_public/shared-ui/about': typeof PublicSharedUiAboutRoute
  '/_public/shared-ui/blog': typeof PublicSharedUiBlogRouteWithChildren
  '/_public/shared-ui/careers': typeof PublicSharedUiCareersRoute
  '/_public/shared-ui/contact': typeof PublicSharedUiContactRoute
  '/_public/shared-ui/donate': typeof PublicSharedUiDonateRoute
  '/_public/shared-ui/events': typeof PublicSharedUiEventsRouteWithChildren
  '/_public/shared-ui/faq': typeof PublicSharedUiFaqRoute
  '/_public/shared-ui/listings': typeof PublicSharedUiListingsRoute
  '/_public/shared-ui/local-group': typeof PublicSharedUiLocalGroupRoute
  '/_public/shared-ui/party-position': typeof PublicSharedUiPartyPositionRoute
  '/_public/shared-ui/political-position': typeof PublicSharedUiPoliticalPositionRoute
  '/_public/shared-ui/privacy': typeof PublicSharedUiPrivacyRoute
  '/_public/shared-ui/publications': typeof PublicSharedUiPublicationsRoute
  '/_public/shared-ui/register': typeof PublicSharedUiRegisterRoute
  '/_public/shared-ui/terms': typeof PublicSharedUiTermsRoute
  '/_public/shared-ui/volunteer': typeof PublicSharedUiVolunteerRoute
  '/_authenticated/admin/ui/admin-users': typeof AuthenticatedAdminUiAdminUsersRoute
  '/_authenticated/admin/ui/applications': typeof AuthenticatedAdminUiApplicationsRoute
  '/_authenticated/admin/ui/aspirants': typeof AuthenticatedAdminUiAspirantsRoute
  '/_authenticated/admin/ui/audit-trails': typeof AuthenticatedAdminUiAuditTrailsRoute
  '/_authenticated/admin/ui/blogs': typeof AuthenticatedAdminUiBlogsRoute
  '/_authenticated/admin/ui/cms': typeof AuthenticatedAdminUiCmsRoute
  '/_authenticated/admin/ui/donations': typeof AuthenticatedAdminUiDonationsRoute
  '/_authenticated/admin/ui/events': typeof AuthenticatedAdminUiEventsRoute
  '/_authenticated/admin/ui/jobs': typeof AuthenticatedAdminUiJobsRouteWithChildren
  '/_authenticated/admin/ui/local-groups': typeof AuthenticatedAdminUiLocalGroupsRoute
  '/_authenticated/admin/ui/members': typeof AuthenticatedAdminUiMembersRoute
  '/_authenticated/admin/ui/merchandise': typeof AuthenticatedAdminUiMerchandiseRoute
  '/_authenticated/admin/ui/reports': typeof AuthenticatedAdminUiReportsRoute
  '/_authenticated/admin/ui/roles': typeof AuthenticatedAdminUiRolesRoute
  '/_authenticated/admin/ui/settings': typeof AuthenticatedAdminUiSettingsRoute
  '/_authenticated/admin/ui/users': typeof AuthenticatedAdminUiUsersRoute
  '/_authenticated/admin/ui/volunteer': typeof AuthenticatedAdminUiVolunteerRoute
  '/_public/events/$id/register': typeof PublicEventsIdRegisterRoute
  '/_public/shared-ui/blog/$id': typeof PublicSharedUiBlogIdRoute
  '/_public/shared-ui/events/$id': typeof PublicSharedUiEventsIdRouteWithChildren
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_public/shared-ui/events/$id/register': typeof PublicSharedUiEventsIdRegisterRoute
  '/_authenticated/admin/ui/jobs/$jobId/applications': typeof AuthenticatedAdminUiJobsJobIdApplicationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/admin'
    | '/portal'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/donate'
    | '/events'
    | '/faq'
    | '/listings'
    | '/local-group'
    | '/party-position'
    | '/political-position'
    | '/privacy'
    | '/publications'
    | '/register'
    | '/terms'
    | '/volunteer'
    | '/admin/dashboard'
    | '/blog/$id'
    | '/events/$id'
    | '/shared-ui/about'
    | '/shared-ui/blog'
    | '/shared-ui/careers'
    | '/shared-ui/contact'
    | '/shared-ui/donate'
    | '/shared-ui/events'
    | '/shared-ui/faq'
    | '/shared-ui/listings'
    | '/shared-ui/local-group'
    | '/shared-ui/party-position'
    | '/shared-ui/political-position'
    | '/shared-ui/privacy'
    | '/shared-ui/publications'
    | '/shared-ui/register'
    | '/shared-ui/terms'
    | '/shared-ui/volunteer'
    | '/admin/ui/admin-users'
    | '/admin/ui/applications'
    | '/admin/ui/aspirants'
    | '/admin/ui/audit-trails'
    | '/admin/ui/blogs'
    | '/admin/ui/cms'
    | '/admin/ui/donations'
    | '/admin/ui/events'
    | '/admin/ui/jobs'
    | '/admin/ui/local-groups'
    | '/admin/ui/members'
    | '/admin/ui/merchandise'
    | '/admin/ui/reports'
    | '/admin/ui/roles'
    | '/admin/ui/settings'
    | '/admin/ui/users'
    | '/admin/ui/volunteer'
    | '/events/$id/register'
    | '/shared-ui/blog/$id'
    | '/shared-ui/events/$id'
    | '/lovable/email/queue/process'
    | '/shared-ui/events/$id/register'
    | '/admin/ui/jobs/$jobId/applications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/admin'
    | '/portal'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/donate'
    | '/events'
    | '/faq'
    | '/listings'
    | '/local-group'
    | '/party-position'
    | '/political-position'
    | '/privacy'
    | '/publications'
    | '/register'
    | '/terms'
    | '/volunteer'
    | '/admin/dashboard'
    | '/blog/$id'
    | '/events/$id'
    | '/shared-ui/about'
    | '/shared-ui/blog'
    | '/shared-ui/careers'
    | '/shared-ui/contact'
    | '/shared-ui/donate'
    | '/shared-ui/events'
    | '/shared-ui/faq'
    | '/shared-ui/listings'
    | '/shared-ui/local-group'
    | '/shared-ui/party-position'
    | '/shared-ui/political-position'
    | '/shared-ui/privacy'
    | '/shared-ui/publications'
    | '/shared-ui/register'
    | '/shared-ui/terms'
    | '/shared-ui/volunteer'
    | '/admin/ui/admin-users'
    | '/admin/ui/applications'
    | '/admin/ui/aspirants'
    | '/admin/ui/audit-trails'
    | '/admin/ui/blogs'
    | '/admin/ui/cms'
    | '/admin/ui/donations'
    | '/admin/ui/events'
    | '/admin/ui/jobs'
    | '/admin/ui/local-groups'
    | '/admin/ui/members'
    | '/admin/ui/merchandise'
    | '/admin/ui/reports'
    | '/admin/ui/roles'
    | '/admin/ui/settings'
    | '/admin/ui/users'
    | '/admin/ui/volunteer'
    | '/events/$id/register'
    | '/shared-ui/blog/$id'
    | '/shared-ui/events/$id'
    | '/lovable/email/queue/process'
    | '/shared-ui/events/$id/register'
    | '/admin/ui/jobs/$jobId/applications'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/_public/about'
    | '/_public/blog'
    | '/_public/careers'
    | '/_public/contact'
    | '/_public/donate'
    | '/_public/events'
    | '/_public/faq'
    | '/_public/listings'
    | '/_public/local-group'
    | '/_public/party-position'
    | '/_public/political-position'
    | '/_public/privacy'
    | '/_public/publications'
    | '/_public/register'
    | '/_public/terms'
    | '/_public/volunteer'
    | '/_public/'
    | '/_authenticated/admin/dashboard'
    | '/_public/blog/$id'
    | '/_public/events/$id'
    | '/_public/shared-ui/about'
    | '/_public/shared-ui/blog'
    | '/_public/shared-ui/careers'
    | '/_public/shared-ui/contact'
    | '/_public/shared-ui/donate'
    | '/_public/shared-ui/events'
    | '/_public/shared-ui/faq'
    | '/_public/shared-ui/listings'
    | '/_public/shared-ui/local-group'
    | '/_public/shared-ui/party-position'
    | '/_public/shared-ui/political-position'
    | '/_public/shared-ui/privacy'
    | '/_public/shared-ui/publications'
    | '/_public/shared-ui/register'
    | '/_public/shared-ui/terms'
    | '/_public/shared-ui/volunteer'
    | '/_authenticated/admin/ui/admin-users'
    | '/_authenticated/admin/ui/applications'
    | '/_authenticated/admin/ui/aspirants'
    | '/_authenticated/admin/ui/audit-trails'
    | '/_authenticated/admin/ui/blogs'
    | '/_authenticated/admin/ui/cms'
    | '/_authenticated/admin/ui/donations'
    | '/_authenticated/admin/ui/events'
    | '/_authenticated/admin/ui/jobs'
    | '/_authenticated/admin/ui/local-groups'
    | '/_authenticated/admin/ui/members'
    | '/_authenticated/admin/ui/merchandise'
    | '/_authenticated/admin/ui/reports'
    | '/_authenticated/admin/ui/roles'
    | '/_authenticated/admin/ui/settings'
    | '/_authenticated/admin/ui/users'
    | '/_authenticated/admin/ui/volunteer'
    | '/_public/events/$id/register'
    | '/_public/shared-ui/blog/$id'
    | '/_public/shared-ui/events/$id'
    | '/lovable/email/queue/process'
    | '/_public/shared-ui/events/$id/register'
    | '/_authenticated/admin/ui/jobs/$jobId/applications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OtpRoute: typeof OtpRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/volunteer': {
      id: '/_public/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof PublicVolunteerRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/publications': {
      id: '/_public/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicPublicationsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/political-position': {
      id: '/_public/political-position'
      path: '/political-position'
      fullPath: '/political-position'
      preLoaderRoute: typeof PublicPoliticalPositionRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/party-position': {
      id: '/_public/party-position'
      path: '/party-position'
      fullPath: '/party-position'
      preLoaderRoute: typeof PublicPartyPositionRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/local-group': {
      id: '/_public/local-group'
      path: '/local-group'
      fullPath: '/local-group'
      preLoaderRoute: typeof PublicLocalGroupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/listings': {
      id: '/_public/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof PublicListingsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/events': {
      id: '/_public/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof PublicEventsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/donate': {
      id: '/_public/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof PublicDonateRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/careers': {
      id: '/_public/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof PublicCareersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog': {
      id: '/_public/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof PublicBlogRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/shared-ui/volunteer': {
      id: '/_public/shared-ui/volunteer'
      path: '/shared-ui/volunteer'
      fullPath: '/shared-ui/volunteer'
      preLoaderRoute: typeof PublicSharedUiVolunteerRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/shared-ui/terms': {
      id: '/_public/shared-ui/terms'
      path: '/shared-ui/terms'
      fullPath: '/shared-ui/terms'
      preLoaderRoute: typeof PublicSharedUiTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/shared-ui/register': {
      id: '/_public/shared-ui/register'
      path: '/shared-ui/register'
      fullPath: '/shared-ui/register'
      preLoaderRoute: typeof PublicSharedUiRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/shared-ui/publications': {
      id: '/_public/shared-ui/publications'
      path: '/shared-ui/publications'
      fullPath: '/shared-ui/publications'
      preLoaderRoute: typeof PublicSharedUiPublicationsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/shared-ui/privacy': {
      id: '/_public/shared-ui/privacy'
      path: '/shared-ui/privacy'
      fullPath: '/shared-ui/privacy'
      preLoaderRoute: typeof PublicSharedUiPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/shared-ui/political-position': {
      id: '/_public/shared-ui/political-position'
      path: '/shared-ui/political-position'
      fullPath: '/shared-ui/political-position'
      preLoaderRoute: typeof PublicSharedUiPoliticalPositionRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/shared-ui/party-position': {
      id: '/_public/shared-ui/party-position'
      path: '/shared-ui/party-position'
      fullPath: '/shared-ui/party-position'
      preLoaderRoute: typeof PublicSharedUiPartyPositionRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/shared-ui/local-group': {
      id: '/_public/shared-ui/local-group'
      path: '/shared-ui/local-group'
      fullPath: '/shared-ui/local-group'
      preLoaderRoute: typeof PublicSharedUiLocalGroupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/shared-ui/listings': {
      id: '/_public/shared-ui/listings'
      path: '/shared-ui/listings'
      fullPath: '/shared-ui/listings'
      preLoaderRoute: typeof PublicSharedUiListingsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/shared-ui/faq': {
      id: '/_public/shared-ui/faq'
      path: '/shared-ui/faq'
      fullPath: '/shared-ui/faq'
      preLoaderRoute: typeof PublicSharedUiFaqRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/shared-ui/events': {
      id: '/_public/shared-ui/events'
      path: '/shared-ui/events'
      fullPath: '/shared-ui/events'
      preLoaderRoute: typeof PublicSharedUiEventsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/shared-ui/donate': {
      id: '/_public/shared-ui/donate'
      path: '/shared-ui/donate'
      fullPath: '/shared-ui/donate'
      preLoaderRoute: typeof PublicSharedUiDonateRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/shared-ui/contact': {
      id: '/_public/shared-ui/contact'
      path: '/shared-ui/contact'
      fullPath: '/shared-ui/contact'
      preLoaderRoute: typeof PublicSharedUiContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/shared-ui/careers': {
      id: '/_public/shared-ui/careers'
      path: '/shared-ui/careers'
      fullPath: '/shared-ui/careers'
      preLoaderRoute: typeof PublicSharedUiCareersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/shared-ui/blog': {
      id: '/_public/shared-ui/blog'
      path: '/shared-ui/blog'
      fullPath: '/shared-ui/blog'
      preLoaderRoute: typeof PublicSharedUiBlogRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/shared-ui/about': {
      id: '/_public/shared-ui/about'
      path: '/shared-ui/about'
      fullPath: '/shared-ui/about'
      preLoaderRoute: typeof PublicSharedUiAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/events/$id': {
      id: '/_public/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof PublicEventsIdRouteImport
      parentRoute: typeof PublicEventsRoute
    }
    '/_public/blog/$id': {
      id: '/_public/blog/$id'
      path: '/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof PublicBlogIdRouteImport
      parentRoute: typeof PublicBlogRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/shared-ui/events/$id': {
      id: '/_public/shared-ui/events/$id'
      path: '/$id'
      fullPath: '/shared-ui/events/$id'
      preLoaderRoute: typeof PublicSharedUiEventsIdRouteImport
      parentRoute: typeof PublicSharedUiEventsRoute
    }
    '/_public/shared-ui/blog/$id': {
      id: '/_public/shared-ui/blog/$id'
      path: '/$id'
      fullPath: '/shared-ui/blog/$id'
      preLoaderRoute: typeof PublicSharedUiBlogIdRouteImport
      parentRoute: typeof PublicSharedUiBlogRoute
    }
    '/_public/events/$id/register': {
      id: '/_public/events/$id/register'
      path: '/register'
      fullPath: '/events/$id/register'
      preLoaderRoute: typeof PublicEventsIdRegisterRouteImport
      parentRoute: typeof PublicEventsIdRoute
    }
    '/_authenticated/admin/ui/volunteer': {
      id: '/_authenticated/admin/ui/volunteer'
      path: '/ui/volunteer'
      fullPath: '/admin/ui/volunteer'
      preLoaderRoute: typeof AuthenticatedAdminUiVolunteerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ui/users': {
      id: '/_authenticated/admin/ui/users'
      path: '/ui/users'
      fullPath: '/admin/ui/users'
      preLoaderRoute: typeof AuthenticatedAdminUiUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ui/settings': {
      id: '/_authenticated/admin/ui/settings'
      path: '/ui/settings'
      fullPath: '/admin/ui/settings'
      preLoaderRoute: typeof AuthenticatedAdminUiSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ui/roles': {
      id: '/_authenticated/admin/ui/roles'
      path: '/ui/roles'
      fullPath: '/admin/ui/roles'
      preLoaderRoute: typeof AuthenticatedAdminUiRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ui/reports': {
      id: '/_authenticated/admin/ui/reports'
      path: '/ui/reports'
      fullPath: '/admin/ui/reports'
      preLoaderRoute: typeof AuthenticatedAdminUiReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ui/merchandise': {
      id: '/_authenticated/admin/ui/merchandise'
      path: '/ui/merchandise'
      fullPath: '/admin/ui/merchandise'
      preLoaderRoute: typeof AuthenticatedAdminUiMerchandiseRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ui/members': {
      id: '/_authenticated/admin/ui/members'
      path: '/ui/members'
      fullPath: '/admin/ui/members'
      preLoaderRoute: typeof AuthenticatedAdminUiMembersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ui/local-groups': {
      id: '/_authenticated/admin/ui/local-groups'
      path: '/ui/local-groups'
      fullPath: '/admin/ui/local-groups'
      preLoaderRoute: typeof AuthenticatedAdminUiLocalGroupsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ui/jobs': {
      id: '/_authenticated/admin/ui/jobs'
      path: '/ui/jobs'
      fullPath: '/admin/ui/jobs'
      preLoaderRoute: typeof AuthenticatedAdminUiJobsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ui/events': {
      id: '/_authenticated/admin/ui/events'
      path: '/ui/events'
      fullPath: '/admin/ui/events'
      preLoaderRoute: typeof AuthenticatedAdminUiEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ui/donations': {
      id: '/_authenticated/admin/ui/donations'
      path: '/ui/donations'
      fullPath: '/admin/ui/donations'
      preLoaderRoute: typeof AuthenticatedAdminUiDonationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ui/cms': {
      id: '/_authenticated/admin/ui/cms'
      path: '/ui/cms'
      fullPath: '/admin/ui/cms'
      preLoaderRoute: typeof AuthenticatedAdminUiCmsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ui/blogs': {
      id: '/_authenticated/admin/ui/blogs'
      path: '/ui/blogs'
      fullPath: '/admin/ui/blogs'
      preLoaderRoute: typeof AuthenticatedAdminUiBlogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ui/audit-trails': {
      id: '/_authenticated/admin/ui/audit-trails'
      path: '/ui/audit-trails'
      fullPath: '/admin/ui/audit-trails'
      preLoaderRoute: typeof AuthenticatedAdminUiAuditTrailsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ui/aspirants': {
      id: '/_authenticated/admin/ui/aspirants'
      path: '/ui/aspirants'
      fullPath: '/admin/ui/aspirants'
      preLoaderRoute: typeof AuthenticatedAdminUiAspirantsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ui/applications': {
      id: '/_authenticated/admin/ui/applications'
      path: '/ui/applications'
      fullPath: '/admin/ui/applications'
      preLoaderRoute: typeof AuthenticatedAdminUiApplicationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ui/admin-users': {
      id: '/_authenticated/admin/ui/admin-users'
      path: '/ui/admin-users'
      fullPath: '/admin/ui/admin-users'
      preLoaderRoute: typeof AuthenticatedAdminUiAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_public/shared-ui/events/$id/register': {
      id: '/_public/shared-ui/events/$id/register'
      path: '/register'
      fullPath: '/shared-ui/events/$id/register'
      preLoaderRoute: typeof PublicSharedUiEventsIdRegisterRouteImport
      parentRoute: typeof PublicSharedUiEventsIdRoute
    }
    '/_authenticated/admin/ui/jobs/$jobId/applications': {
      id: '/_authenticated/admin/ui/jobs/$jobId/applications'
      path: '/$jobId/applications'
      fullPath: '/admin/ui/jobs/$jobId/applications'
      preLoaderRoute: typeof AuthenticatedAdminUiJobsJobIdApplicationsRouteImport
      parentRoute: typeof AuthenticatedAdminUiJobsRoute
    }
  }
}

interface AuthenticatedAdminUiJobsRouteChildren {
  AuthenticatedAdminUiJobsJobIdApplicationsRoute: typeof AuthenticatedAdminUiJobsJobIdApplicationsRoute
}

const AuthenticatedAdminUiJobsRouteChildren: AuthenticatedAdminUiJobsRouteChildren =
  {
    AuthenticatedAdminUiJobsJobIdApplicationsRoute:
      AuthenticatedAdminUiJobsJobIdApplicationsRoute,
  }

const AuthenticatedAdminUiJobsRouteWithChildren =
  AuthenticatedAdminUiJobsRoute._addFileChildren(
    AuthenticatedAdminUiJobsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminUiAdminUsersRoute: typeof AuthenticatedAdminUiAdminUsersRoute
  AuthenticatedAdminUiApplicationsRoute: typeof AuthenticatedAdminUiApplicationsRoute
  AuthenticatedAdminUiAspirantsRoute: typeof AuthenticatedAdminUiAspirantsRoute
  AuthenticatedAdminUiAuditTrailsRoute: typeof AuthenticatedAdminUiAuditTrailsRoute
  AuthenticatedAdminUiBlogsRoute: typeof AuthenticatedAdminUiBlogsRoute
  AuthenticatedAdminUiCmsRoute: typeof AuthenticatedAdminUiCmsRoute
  AuthenticatedAdminUiDonationsRoute: typeof AuthenticatedAdminUiDonationsRoute
  AuthenticatedAdminUiEventsRoute: typeof AuthenticatedAdminUiEventsRoute
  AuthenticatedAdminUiJobsRoute: typeof AuthenticatedAdminUiJobsRouteWithChildren
  AuthenticatedAdminUiLocalGroupsRoute: typeof AuthenticatedAdminUiLocalGroupsRoute
  AuthenticatedAdminUiMembersRoute: typeof AuthenticatedAdminUiMembersRoute
  AuthenticatedAdminUiMerchandiseRoute: typeof AuthenticatedAdminUiMerchandiseRoute
  AuthenticatedAdminUiReportsRoute: typeof AuthenticatedAdminUiReportsRoute
  AuthenticatedAdminUiRolesRoute: typeof AuthenticatedAdminUiRolesRoute
  AuthenticatedAdminUiSettingsRoute: typeof AuthenticatedAdminUiSettingsRoute
  AuthenticatedAdminUiUsersRoute: typeof AuthenticatedAdminUiUsersRoute
  AuthenticatedAdminUiVolunteerRoute: typeof AuthenticatedAdminUiVolunteerRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminUiAdminUsersRoute: AuthenticatedAdminUiAdminUsersRoute,
  AuthenticatedAdminUiApplicationsRoute: AuthenticatedAdminUiApplicationsRoute,
  AuthenticatedAdminUiAspirantsRoute: AuthenticatedAdminUiAspirantsRoute,
  AuthenticatedAdminUiAuditTrailsRoute: AuthenticatedAdminUiAuditTrailsRoute,
  AuthenticatedAdminUiBlogsRoute: AuthenticatedAdminUiBlogsRoute,
  AuthenticatedAdminUiCmsRoute: AuthenticatedAdminUiCmsRoute,
  AuthenticatedAdminUiDonationsRoute: AuthenticatedAdminUiDonationsRoute,
  AuthenticatedAdminUiEventsRoute: AuthenticatedAdminUiEventsRoute,
  AuthenticatedAdminUiJobsRoute: AuthenticatedAdminUiJobsRouteWithChildren,
  AuthenticatedAdminUiLocalGroupsRoute: AuthenticatedAdminUiLocalGroupsRoute,
  AuthenticatedAdminUiMembersRoute: AuthenticatedAdminUiMembersRoute,
  AuthenticatedAdminUiMerchandiseRoute: AuthenticatedAdminUiMerchandiseRoute,
  AuthenticatedAdminUiReportsRoute: AuthenticatedAdminUiReportsRoute,
  AuthenticatedAdminUiRolesRoute: AuthenticatedAdminUiRolesRoute,
  AuthenticatedAdminUiSettingsRoute: AuthenticatedAdminUiSettingsRoute,
  AuthenticatedAdminUiUsersRoute: AuthenticatedAdminUiUsersRoute,
  AuthenticatedAdminUiVolunteerRoute: AuthenticatedAdminUiVolunteerRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicBlogRouteChildren {
  PublicBlogIdRoute: typeof PublicBlogIdRoute
}

const PublicBlogRouteChildren: PublicBlogRouteChildren = {
  PublicBlogIdRoute: PublicBlogIdRoute,
}

const PublicBlogRouteWithChildren = PublicBlogRoute._addFileChildren(
  PublicBlogRouteChildren,
)

interface PublicEventsIdRouteChildren {
  PublicEventsIdRegisterRoute: typeof PublicEventsIdRegisterRoute
}

const PublicEventsIdRouteChildren: PublicEventsIdRouteChildren = {
  PublicEventsIdRegisterRoute: PublicEventsIdRegisterRoute,
}

const PublicEventsIdRouteWithChildren = PublicEventsIdRoute._addFileChildren(
  PublicEventsIdRouteChildren,
)

interface PublicEventsRouteChildren {
  PublicEventsIdRoute: typeof PublicEventsIdRouteWithChildren
}

const PublicEventsRouteChildren: PublicEventsRouteChildren = {
  PublicEventsIdRoute: PublicEventsIdRouteWithChildren,
}

const PublicEventsRouteWithChildren = PublicEventsRoute._addFileChildren(
  PublicEventsRouteChildren,
)

interface PublicSharedUiBlogRouteChildren {
  PublicSharedUiBlogIdRoute: typeof PublicSharedUiBlogIdRoute
}

const PublicSharedUiBlogRouteChildren: PublicSharedUiBlogRouteChildren = {
  PublicSharedUiBlogIdRoute: PublicSharedUiBlogIdRoute,
}

const PublicSharedUiBlogRouteWithChildren =
  PublicSharedUiBlogRoute._addFileChildren(PublicSharedUiBlogRouteChildren)

interface PublicSharedUiEventsIdRouteChildren {
  PublicSharedUiEventsIdRegisterRoute: typeof PublicSharedUiEventsIdRegisterRoute
}

const PublicSharedUiEventsIdRouteChildren: PublicSharedUiEventsIdRouteChildren =
  {
    PublicSharedUiEventsIdRegisterRoute: PublicSharedUiEventsIdRegisterRoute,
  }

const PublicSharedUiEventsIdRouteWithChildren =
  PublicSharedUiEventsIdRoute._addFileChildren(
    PublicSharedUiEventsIdRouteChildren,
  )

interface PublicSharedUiEventsRouteChildren {
  PublicSharedUiEventsIdRoute: typeof PublicSharedUiEventsIdRouteWithChildren
}

const PublicSharedUiEventsRouteChildren: PublicSharedUiEventsRouteChildren = {
  PublicSharedUiEventsIdRoute: PublicSharedUiEventsIdRouteWithChildren,
}

const PublicSharedUiEventsRouteWithChildren =
  PublicSharedUiEventsRoute._addFileChildren(PublicSharedUiEventsRouteChildren)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicBlogRoute: typeof PublicBlogRouteWithChildren
  PublicCareersRoute: typeof PublicCareersRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicDonateRoute: typeof PublicDonateRoute
  PublicEventsRoute: typeof PublicEventsRouteWithChildren
  PublicFaqRoute: typeof PublicFaqRoute
  PublicListingsRoute: typeof PublicListingsRoute
  PublicLocalGroupRoute: typeof PublicLocalGroupRoute
  PublicPartyPositionRoute: typeof PublicPartyPositionRoute
  PublicPoliticalPositionRoute: typeof PublicPoliticalPositionRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicPublicationsRoute: typeof PublicPublicationsRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicVolunteerRoute: typeof PublicVolunteerRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicSharedUiAboutRoute: typeof PublicSharedUiAboutRoute
  PublicSharedUiBlogRoute: typeof PublicSharedUiBlogRouteWithChildren
  PublicSharedUiCareersRoute: typeof PublicSharedUiCareersRoute
  PublicSharedUiContactRoute: typeof PublicSharedUiContactRoute
  PublicSharedUiDonateRoute: typeof PublicSharedUiDonateRoute
  PublicSharedUiEventsRoute: typeof PublicSharedUiEventsRouteWithChildren
  PublicSharedUiFaqRoute: typeof PublicSharedUiFaqRoute
  PublicSharedUiListingsRoute: typeof PublicSharedUiListingsRoute
  PublicSharedUiLocalGroupRoute: typeof PublicSharedUiLocalGroupRoute
  PublicSharedUiPartyPositionRoute: typeof PublicSharedUiPartyPositionRoute
  PublicSharedUiPoliticalPositionRoute: typeof PublicSharedUiPoliticalPositionRoute
  PublicSharedUiPrivacyRoute: typeof PublicSharedUiPrivacyRoute
  PublicSharedUiPublicationsRoute: typeof PublicSharedUiPublicationsRoute
  PublicSharedUiRegisterRoute: typeof PublicSharedUiRegisterRoute
  PublicSharedUiTermsRoute: typeof PublicSharedUiTermsRoute
  PublicSharedUiVolunteerRoute: typeof PublicSharedUiVolunteerRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicBlogRoute: PublicBlogRouteWithChildren,
  PublicCareersRoute: PublicCareersRoute,
  PublicContactRoute: PublicContactRoute,
  PublicDonateRoute: PublicDonateRoute,
  PublicEventsRoute: PublicEventsRouteWithChildren,
  PublicFaqRoute: PublicFaqRoute,
  PublicListingsRoute: PublicListingsRoute,
  PublicLocalGroupRoute: PublicLocalGroupRoute,
  PublicPartyPositionRoute: PublicPartyPositionRoute,
  PublicPoliticalPositionRoute: PublicPoliticalPositionRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicPublicationsRoute: PublicPublicationsRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicVolunteerRoute: PublicVolunteerRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicSharedUiAboutRoute: PublicSharedUiAboutRoute,
  PublicSharedUiBlogRoute: PublicSharedUiBlogRouteWithChildren,
  PublicSharedUiCareersRoute: PublicSharedUiCareersRoute,
  PublicSharedUiContactRoute: PublicSharedUiContactRoute,
  PublicSharedUiDonateRoute: PublicSharedUiDonateRoute,
  PublicSharedUiEventsRoute: PublicSharedUiEventsRouteWithChildren,
  PublicSharedUiFaqRoute: PublicSharedUiFaqRoute,
  PublicSharedUiListingsRoute: PublicSharedUiListingsRoute,
  PublicSharedUiLocalGroupRoute: PublicSharedUiLocalGroupRoute,
  PublicSharedUiPartyPositionRoute: PublicSharedUiPartyPositionRoute,
  PublicSharedUiPoliticalPositionRoute: PublicSharedUiPoliticalPositionRoute,
  PublicSharedUiPrivacyRoute: PublicSharedUiPrivacyRoute,
  PublicSharedUiPublicationsRoute: PublicSharedUiPublicationsRoute,
  PublicSharedUiRegisterRoute: PublicSharedUiRegisterRoute,
  PublicSharedUiTermsRoute: PublicSharedUiTermsRoute,
  PublicSharedUiVolunteerRoute: PublicSharedUiVolunteerRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OtpRoute: OtpRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
